In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("Cloud_Sense_CSV.csv")

In [7]:

df.head(40)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   record_id         200 non-null    int64
 1   date              200 non-null    object
 2   storage_gb        200 non-null    int64
 3   allocated_cost    200 non-null    int64
 4   actual_used_cost  200 non-null    int64
 5   service_clean     200 non-null    object
 6   region_clean      200 non-null    object
 7   status_clean      200 non-null    object
 8   waste_cost        200 non-null    int64
 9   waste_percent     200 non-null    object
 10  cpu_clean         200 non-null    float64
dtypes: float64(1), int64(5), object(5)
memory usage: 17.3+ KB

In [ ]:
# Basic data Exploration

In [8]:
df.describe()

,record_id,storage_gb,allocated_cost,actual_used_cost,waste_cost,cpu_clean
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,100.500000,263.455000,530.000000,370.210000,159.790000,47.111111
std,57.879185,178.286986,158.827361,229.167569,135.497542,31.854148
min,1.000000,12.000000,200.000000,35.000000,0.000000,2.000000
25%,50.750000,108.000000,500.000000,148.750000,24.250000,16.750000
50%,100.500000,247.500000,550.000000,377.500000,149.000000,44.500000
75%,150.250000,400.000000,625.000000,592.750000,240.000000,78.000000
max,200.000000,595.000000,700.000000,700.000000,450.000000,100.000000

In [18]:
#which service waste the most  ?
service_waste=df.groupby('service_clean').agg({
    'allocated_cost':'sum',
    'waste_cost':'sum'}).reset_index()
print(service_waste)

  service_clean  allocated_cost  waste_cost
0           EC2           35000       16885
1        LAMBDA            6000        4467
2           RDS           30000        7111
3            S3           35000        3495

In [21]:
#Which cloud services consume the most cost?

service_cost=df.groupby('service_clean')['actual_used_cost'].sum().reset_index()
print(service_cost)

service_cost.to_csv("serviceCost_summary.csv",index=False)

  service_clean  actual_used_cost
0           EC2             18115
1        LAMBDA              1533
2           RDS             22889
3            S3             31505

In [25]:
# which region is costing the most.?

region_cost=df.groupby('region_clean')['actual_used_cost'].sum().reset_index()
region_cost.to_csv("RegionCost_summary.csv",index=False)
print(region_cost)

  region_clean  actual_used_cost
0   asia-south              7102
1   eu-central             16906
2      us-east             18115
3      us-west             31919

In [29]:
# calculate waste percentage.
#df['waste_percent']=(df['waste_cost']/df['allocated_cost'])*100

df1=df[['service_clean','allocated_cost','waste_cost','waste_percent']]
df1.to_csv("WastePercent_summary.csv",index=False)

In [32]:
# which resource IDs are costing the most.
top_resources=df.sort_values(by='actual_used_cost',ascending=False).head(5)
top_resources.to_csv("topResources5.csv",index=False)
top_resources

,record_id,date,storage_gb,allocated_cost,actual_used_cost,service_clean,region_clean,status_clean,waste_cost,waste_percent,cpu_clean
37,38,19-01-2025,560,700,700,S3,us-west,Active,0,0.0,93.0
57,58,29-01-2025,565,700,700,S3,us-west,Active,0,0.0,94.0
17,18,09-01-2025,550,700,700,S3,us-west,Active,0,0.0,92.0
177,178,30-03-2025,590,700,700,S3,us-west,Active,0,0.0,100.0
137,138,10-03-2025,580,700,700,S3,us-west,Active,0,0.0,98.0

In [33]:
df.to_csv("cloud_cleaned_data.csv",index=False)